/**
 * Loads the wasm engine.
 *
 * A thin wrapper so nothing else imports from `../wasm/` directly — that
 * directory is wasm-pack output, regenerated by `pnpm build:wasm` and not
 * committed.
 */

import init, { Terminal, encodeKey, encodeMouse } from "../wasm/celeritty.js";
import type { InitInput } from "../wasm/celeritty.js";

let initialized: Promise<void> | undefined;
let memory: WebAssembly.Memory | undefined;

/**
 * Initialize the wasm module, once per process. Safe to call from several
 * terminals mounting concurrently — they all await the same promise.
 *
 * `input` is optional: browsers rely on the module's own URL resolution.
 * Node test runners cannot fetch that URL (vitest rewrites `import.meta.url`
 * to a dead dev-server address), so tests pass the wasm bytes read from disk.
 *
 * Throws when WebAssembly cannot be instantiated — for instance under a CSP
 * without `'wasm-unsafe-eval'` — rather than leaving the caller holding an
 * unusable module.
 */
export async function loadEngine(input?: InitInput): Promise<void> {
  if (initialized === undefined) {
    initialized = init(input).then((instance) => {
      memory = instance.memory;
    });
  }
  await initialized;
}

/**
 * The wasm module's linear memory buffer.
 *
 * Call this every time you need a view; never cache the result. Any Rust
 * allocation can grow the memory, which detaches every previously created
 * typed array over it — a cached view then reads zeroes, silently.
 */
export function engineMemory(): ArrayBuffer {
  if (memory === undefined) {
    throw new Error("The wasm engine has not been loaded — call loadEngine() first.");
  }
  return memory.buffer;
}

export { Terminal as EngineTerminal, encodeKey, encodeMouse };
